# Generated by Django 2.2.7 on 2021-12-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='car_thumbnails')),
                ('img1', models.ImageField(upload_to='car_covers')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute', models.CharField(blank=True, max_length=100, null=True)),
                ('decription', models.TextField()),
                ('price', models.IntegerField()),
                ('car_type', models.CharField(default='Hatchback', max_length=40)),
                ('gear_type', models.CharField(default='Manual', max_length=40)),
                ('colour', models.CharField(max_length=40)),
                ('petrol_type', models.CharField(default='Diesel', max_length=40)),
                ('mileage', models.IntegerField()),
                ('year_of_car', models.IntegerField()),
                ('model_series', models.CharField(default='N/A', max_length=50)),
                ('gross_weight_kg', models.IntegerField(default='N/A')),
                ('acceleration_zeroToSixty', models.FloatField(default='N/A')),
                ('fuel_consumption_MPG', models.FloatField(default='N/A')),
                ('foward_gears', models.IntegerField(default='N/A')),
                ('max_power_BHP', models.IntegerField(default='N/A')),
                ('max_speed_MPH', models.IntegerField(default='N/A')),
                ('number_of_cylinders', models.IntegerField(default='N/A')),
                ('length_metres', models.FloatField(default='N/A')),
                ('height_metres', models.FloatField(default='N/A')),
                ('slug', models.SlugField(default='please-input-in-this-format', max_length=100)),
            ],
        ),
    ]
