# Generated by Django 2.2.7 on 2021-12-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='car_thumbnails')),
                ('thumbnail_description', models.CharField(default='', max_length=500)),
                ('img1', models.ImageField(upload_to='car_covers')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='car_covers')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('car_type', models.CharField(default='Hatchback', max_length=40)),
                ('gear_type', models.CharField(default='Manual', max_length=40)),
                ('colour', models.CharField(max_length=40)),
                ('petrol_type', models.CharField(default='Diesel', max_length=40)),
                ('mileage', models.IntegerField()),
                ('year_of_car', models.IntegerField()),
                ('model_series', models.CharField(blank=True, max_length=50, null=True)),
                ('gross_weight_kg', models.IntegerField(blank=True, null=True)),
                ('acceleration_zeroToSixty', models.FloatField(blank=True, null=True)),
                ('fuel_consumption_MPG', models.FloatField(blank=True, null=True)),
                ('foward_gears', models.IntegerField(blank=True, null=True)),
                ('max_power_BHP', models.IntegerField(blank=True, null=True)),
                ('max_speed_MPH', models.IntegerField(blank=True, null=True)),
                ('number_of_cylinders', models.IntegerField(blank=True, null=True)),
                ('length_metres', models.FloatField(blank=True, null=True)),
                ('height_metres', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(default='please-input-in-this-format', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='promotional')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Car')),
            ],
        ),
    ]
