# Generated by Django 2.2.7 on 2021-12-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20211206_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='thumbnail_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
