# Generated by Django 2.2.7 on 2021-12-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20211207_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotionalCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='promotional')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Car')),
            ],
        ),
    ]
