# Generated by Django 2.2.7 on 2021-12-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'db_table': 'testimonials',
            },
        ),
        migrations.CreateModel(
            name='PopularCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_car', to='stock.Car')),
            ],
        ),
    ]
